[package]
name = "rxopticsnif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "rxopticsnif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.26.0"
image = "0.23.14"
imageproc = "0.22.0"